/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LokSabhaRouteImport } from './routes/lok-sabha'
import { Route as RajyaSabhaRouteImport } from './routes/rajya-sabha'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LokSabhaRoute = LokSabhaRouteImport.update({
  id: '/lok-sabha',
  path: '/lok-sabha',
  getParentRoute: () => rootRouteImport,
} as any)
const RajyaSabhaRoute = RajyaSabhaRouteImport.update({
  id: '/rajya-sabha',
  path: '/rajya-sabha',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lok-sabha': typeof LokSabhaRoute
  '/rajya-sabha': typeof RajyaSabhaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lok-sabha': typeof LokSabhaRoute
  '/rajya-sabha': typeof RajyaSabhaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lok-sabha': typeof LokSabhaRoute
  '/rajya-sabha': typeof RajyaSabhaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lok-sabha' | '/rajya-sabha'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lok-sabha' | '/rajya-sabha'
  id: '__root__' | '/' | '/lok-sabha' | '/rajya-sabha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LokSabhaRoute: typeof LokSabhaRoute
  RajyaSabhaRoute: typeof RajyaSabhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lok-sabha': {
      id: '/lok-sabha'
      path: '/lok-sabha'
      fullPath: '/lok-sabha'
      preLoaderRoute: typeof LokSabhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rajya-sabha': {
      id: '/rajya-sabha'
      path: '/rajya-sabha'
      fullPath: '/rajya-sabha'
      preLoaderRoute: typeof RajyaSabhaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LokSabhaRoute: LokSabhaRoute,
  RajyaSabhaRoute: RajyaSabhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
