/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RajyaSabhaRouteImport } from './routes/rajya-sabha'
import { Route as ThemeRouteImport } from './routes/theme'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RajyaSabhaRoute = RajyaSabhaRouteImport.update({
  id: '/rajya-sabha',
  path: '/rajya-sabha',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeRoute = ThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rajya-sabha': typeof RajyaSabhaRoute
  '/theme': typeof ThemeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rajya-sabha': typeof RajyaSabhaRoute
  '/theme': typeof ThemeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rajya-sabha': typeof RajyaSabhaRoute
  '/theme': typeof ThemeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rajya-sabha' | '/theme'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rajya-sabha' | '/theme'
  id: '__root__' | '/' | '/rajya-sabha' | '/theme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RajyaSabhaRoute: typeof RajyaSabhaRoute
  ThemeRoute: typeof ThemeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rajya-sabha': {
      id: '/rajya-sabha'
      path: '/rajya-sabha'
      fullPath: '/rajya-sabha'
      preLoaderRoute: typeof RajyaSabhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RajyaSabhaRoute: RajyaSabhaRoute,
  ThemeRoute: ThemeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
